export type StatusContainer =
  | 'ARRIVED'
  | 'PENDING_DOCUMENTATION'
  | 'DOCUMENTATION_CREATED'
  | 'INSPECTION_REQUESTED'
  | 'INSPECTION_APPROVED'
  | 'INSPECTION_REJECTED'
  | 'CUSTOMS_CLEARED'
  | 'BLOCKED'
  | 'STORED_IN_YARD'
  | 'RELEASED';
