name: Setup NodeJs and dependencies
description: Setup NodeJs, PNPM and Prisma

runs:
  using: "composite"
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v3

    - name: Setup NodeJs
      uses: actions/setup-node@v4
      with:
        node-version: 22.18.0
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
