// Generated by nestjs-docfy — edit freely, use --force to merge new methods
import { docs } from 'nestjs-docfy';
import {
  ApiBody,
  ApiConflictResponse,
  ApiCreatedResponse,
  ApiInternalServerErrorResponse,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiQuery,
  ApiResponse,
  ApiTags,
  ApiUnauthorizedResponse,
} from '@nestjs/swagger';
import { ContainerController } from './container.controller';

type JsonSchema = Record<string, unknown>;

const STATUS_CONTAINER_VALUES = [
  'ARRIVED',
  'PENDING_DOCUMENTATION',
  'DOCUMENTATION_CREATED',
  'INSPECTION_REQUESTED',
  'INSPECTION_APPROVED',
  'INSPECTION_REJECTED',
  'CUSTOMS_CLEARED',
  'BLOCKED',
  'STORED_IN_YARD',
  'RELEASED',
];

const EXAMPLE_TIMESTAMP = '2026-07-09T12:34:56.000Z';

const arrivalRequestExample = {
  containerId: 'CONT-0001',
  shipId: 'SHIP-2048',
  terminalId: 'TERM-07',
  originCountry: 'BR',
  destinationCountry: 'PT',
  cargoType: 'electronics',
};

const arrivalResponseExample = {
  ...arrivalRequestExample,
  statusContainer: 'PENDING_DOCUMENTATION',
  arrivalDate: EXAMPLE_TIMESTAMP,
};

const containerExample = {
  id: 'b2f2e7b7-3d23-4e0f-9a1a-cc0f1f3a4d5d',
  shipId: 'SHIP-2048',
  terminalId: 'TERM-07',
  originCountry: 'BR',
  destinationCountry: 'PT',
  cargoType: 'electronics',
  status: 'PENDING_DOCUMENTATION',
  arrivalDate: EXAMPLE_TIMESTAMP,
  createdAt: EXAMPLE_TIMESTAMP,
  updatedAt: EXAMPLE_TIMESTAMP,
};

const paginationExample = {
  data: [containerExample],
  meta: {
    page: 1,
    perPage: 10,
    totalPages: 1,
    totalItems: 1,
    hasNextPage: false,
    hasPreviousPage: false,
  },
};

const schema = (
  properties: JsonSchema,
  required: string[],
  example?: unknown,
): JsonSchema => ({
  type: 'object',
  properties,
  required,
  ...(example === undefined ? {} : { example }),
});

const envelopeSchema = <T>(
  code: 'OK' | 'CREATED',
  status: number,
  contentSchema: JsonSchema,
  contentExample: T,
): JsonSchema =>
  schema(
    {
      ok: { type: 'boolean', enum: [true], example: true },
      response: schema(
        {
          code: { type: 'string', enum: [code], example: code },
          status: { type: 'number', enum: [status], example: status },
          content: contentSchema,
        },
        ['code', 'status', 'content'],
        { code, status, content: contentExample },
      ),
      timestamp: {
        type: 'string',
        format: 'date-time',
        example: EXAMPLE_TIMESTAMP,
      },
    },
    ['ok', 'response', 'timestamp'],
    {
      ok: true,
      response: { code, status, content: contentExample },
      timestamp: EXAMPLE_TIMESTAMP,
    },
  );

const errorEnvelopeSchema = (
  code: string,
  status: number,
  message: string,
): JsonSchema =>
  schema(
    {
      ok: { type: 'boolean', enum: [false], example: false },
      error: schema(
        {
          code: { type: 'string', enum: [code], example: code },
          status: { type: 'number', enum: [status], example: status },
          message: { type: 'string', example: message },
        },
        ['code', 'status', 'message'],
        { code, status, message },
      ),
      timestamp: {
        type: 'string',
        format: 'date-time',
        example: EXAMPLE_TIMESTAMP,
      },
    },
    ['ok', 'error', 'timestamp'],
    {
      ok: false,
      error: { code, status, message },
      timestamp: EXAMPLE_TIMESTAMP,
    },
  );

const arrivalRequestSchema: JsonSchema = schema(
  {
    containerId: {
      type: 'string',
      example: arrivalRequestExample.containerId,
      description: 'Container identifier provided by the client.',
    },
    shipId: {
      type: 'string',
      example: arrivalRequestExample.shipId,
    },
    terminalId: {
      type: 'string',
      example: arrivalRequestExample.terminalId,
    },
    originCountry: {
      type: 'string',
      example: arrivalRequestExample.originCountry,
    },
    destinationCountry: {
      type: 'string',
      example: arrivalRequestExample.destinationCountry,
    },
    cargoType: {
      type: 'string',
      example: arrivalRequestExample.cargoType,
    },
  },
  [
    'containerId',
    'shipId',
    'terminalId',
    'originCountry',
    'destinationCountry',
    'cargoType',
  ],
  arrivalRequestExample,
);

const containerSchema: JsonSchema = schema(
  {
    id: { type: 'string', example: containerExample.id },
    shipId: { type: 'string', example: containerExample.shipId },
    terminalId: { type: 'string', example: containerExample.terminalId },
    originCountry: { type: 'string', example: containerExample.originCountry },
    destinationCountry: {
      type: 'string',
      example: containerExample.destinationCountry,
    },
    cargoType: { type: 'string', example: containerExample.cargoType },
    status: {
      type: 'string',
      enum: STATUS_CONTAINER_VALUES,
      example: containerExample.status,
    },
    arrivalDate: {
      type: 'string',
      format: 'date-time',
      example: containerExample.arrivalDate,
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
      example: containerExample.createdAt,
    },
    updatedAt: {
      type: 'string',
      format: 'date-time',
      example: containerExample.updatedAt,
    },
  },
  [
    'shipId',
    'terminalId',
    'originCountry',
    'destinationCountry',
    'cargoType',
    'status',
    'arrivalDate',
  ],
  containerExample,
);

const arrivalResponseSchema: JsonSchema = schema(
  {
    containerId: {
      type: 'string',
      example: arrivalResponseExample.containerId,
    },
    shipId: { type: 'string', example: arrivalResponseExample.shipId },
    terminalId: {
      type: 'string',
      example: arrivalResponseExample.terminalId,
    },
    originCountry: {
      type: 'string',
      example: arrivalResponseExample.originCountry,
    },
    destinationCountry: {
      type: 'string',
      example: arrivalResponseExample.destinationCountry,
    },
    cargoType: { type: 'string', example: arrivalResponseExample.cargoType },
    statusContainer: {
      type: 'string',
      enum: STATUS_CONTAINER_VALUES,
      example: arrivalResponseExample.statusContainer,
    },
    arrivalDate: {
      type: 'string',
      format: 'date-time',
      example: arrivalResponseExample.arrivalDate,
    },
  },
  [
    'containerId',
    'shipId',
    'terminalId',
    'originCountry',
    'destinationCountry',
    'cargoType',
    'statusContainer',
    'arrivalDate',
  ],
  arrivalResponseExample,
);

const paginationSchema: JsonSchema = schema(
  {
    data: {
      type: 'array',
      items: containerSchema,
      example: paginationExample.data,
    },
    meta: schema(
      {
        page: { type: 'number', example: paginationExample.meta.page },
        perPage: { type: 'number', example: paginationExample.meta.perPage },
        totalPages: {
          type: 'number',
          example: paginationExample.meta.totalPages,
        },
        totalItems: {
          type: 'number',
          example: paginationExample.meta.totalItems,
        },
        hasNextPage: {
          type: 'boolean',
          example: paginationExample.meta.hasNextPage,
        },
        hasPreviousPage: {
          type: 'boolean',
          example: paginationExample.meta.hasPreviousPage,
        },
      },
      [
        'page',
        'perPage',
        'totalPages',
        'totalItems',
        'hasNextPage',
        'hasPreviousPage',
      ],
      paginationExample.meta,
    ),
  },
  ['data', 'meta'],
  paginationExample,
);

const createdArrivalResponse = envelopeSchema(
  'CREATED',
  201,
  arrivalResponseSchema,
  arrivalResponseExample,
);

const okContainerResponse = envelopeSchema(
  'OK',
  200,
  containerSchema,
  containerExample,
);
const okPaginationResponse = envelopeSchema(
  'OK',
  200,
  paginationSchema,
  paginationExample,
);

const badRequestResponse = errorEnvelopeSchema(
  'BAD_REQUEST',
  400,
  'Invalid request!',
);

const unauthorizedResponse = errorEnvelopeSchema(
  'UNAUTHORIZED',
  401,
  'Container is unauthorized to proceed!',
);

const conflictResponse = errorEnvelopeSchema(
  'CONFLICT',
  409,
  'Container already arrived!',
);

const notFoundResponse = errorEnvelopeSchema(
  'RESOURCE_NOT_FOUND',
  404,
  'Container not found!',
);

const databaseErrorResponse = errorEnvelopeSchema(
  'DATABASE_ERROR',
  500,
  'Database error!',
);

docs(ContainerController, {
  classDecorators: [ApiTags('Container')],
  methods: {
    registerContainerArrival: [
      ApiOperation({
        summary: 'Register container arrival',
      }),
      ApiBody({
        description: 'Payload used to register a container arrival.',
        schema: arrivalRequestSchema,
      }),
      ApiCreatedResponse({
        description: 'Created - the arrival was persisted successfully.',
        schema: createdArrivalResponse,
      }),
      ApiUnauthorizedResponse({
        description:
          'Unauthorized - terminal validation rejected the container.',
        schema: unauthorizedResponse,
      }),
      ApiResponse({
        status: 400,
        description: 'Bad Request - invalid arrival payload.',
        schema: badRequestResponse,
      }),
      ApiConflictResponse({
        description: 'Conflict - the container already exists.',
        schema: conflictResponse,
      }),
      ApiInternalServerErrorResponse({
        description: 'Internal Server Error - database failure.',
        schema: databaseErrorResponse,
      }),
    ],

    findAllContainers: [
      ApiOperation({ summary: 'Find all containers' }),
      ApiQuery({
        name: 'page',
        type: Number,
        required: false,
        description: 'Page number. Defaults to 1.',
      }),
      ApiQuery({
        name: 'perPage',
        type: Number,
        required: false,
        description: 'Items per page. Defaults to 10.',
      }),
      ApiOkResponse({
        description: 'OK - paginated list of containers.',
        schema: okPaginationResponse,
      }),
      ApiInternalServerErrorResponse({
        description: 'Internal Server Error - database failure.',
        schema: databaseErrorResponse,
      }),
    ],

    findContainerByStatus: [
      ApiOperation({ summary: 'Find container by status' }),
      ApiQuery({
        name: 'status',
        type: String,
        required: true,
        description: 'Container status filter.',
        enum: STATUS_CONTAINER_VALUES,
      }),
      ApiQuery({
        name: 'page',
        type: Number,
        required: false,
        description: 'Page number. Defaults to 1.',
      }),
      ApiQuery({
        name: 'perPage',
        type: Number,
        required: false,
        description: 'Items per page. Defaults to 10.',
      }),
      ApiOkResponse({
        description: 'OK - paginated list of containers by status.',
        schema: okPaginationResponse,
      }),
      ApiInternalServerErrorResponse({
        description: 'Internal Server Error - database failure.',
        schema: databaseErrorResponse,
      }),
    ],

    findContainerById: [
      ApiOperation({ summary: 'Find container by id' }),
      ApiParam({
        name: 'containerId',
        type: String,
        description: 'Container UUID.',
      }),
      ApiOkResponse({
        description: 'OK - container found.',
        schema: okContainerResponse,
      }),
      ApiNotFoundResponse({
        description: 'Not Found - the container does not exist.',
        schema: notFoundResponse,
      }),
      ApiInternalServerErrorResponse({
        description: 'Internal Server Error - database failure.',
        schema: databaseErrorResponse,
      }),
    ],

    updateContainerStatus: [
      ApiOperation({ summary: 'Update container status' }),
      ApiParam({
        name: 'containerId',
        type: String,
        description: 'Container UUID.',
      }),
      ApiBody({
        description: 'New status to apply to the container.',
        schema: schema(
          {
            newStatus: {
              type: 'string',
              enum: STATUS_CONTAINER_VALUES,
              example: 'INSPECTION_REQUESTED',
            },
          },
          ['newStatus'],
          { newStatus: 'INSPECTION_REQUESTED' },
        ),
      }),
      ApiResponse({
        status: 400,
        description: 'Bad Request - invalid status payload.',
        schema: badRequestResponse,
      }),
      ApiOkResponse({
        description: 'OK - container status updated.',
        schema: okContainerResponse,
      }),
      ApiInternalServerErrorResponse({
        description: 'Internal Server Error - database failure.',
        schema: databaseErrorResponse,
      }),
    ],
  },
});
