// Generated by nestjs-docfy — edit freely, use --force to merge new methods
import { docs } from 'nestjs-docfy';
import { ApiOkResponse, ApiOperation, ApiTags } from '@nestjs/swagger';
import { HealthcheckController } from './healthcheck.controller';

const healthExample = {
  ok: true,
  response: {
    code: 'OK',
    status: 200,
    content: 'Container service UP!',
  },
  timestamp: '2026-07-09T12:34:56.000Z',
};

const healthResponseSchema = {
  type: 'object',
  properties: {
    ok: { type: 'boolean', enum: [true], example: true },
    response: {
      type: 'object',
      properties: {
        code: { type: 'string', enum: ['OK'], example: 'OK' },
        status: { type: 'number', enum: [200], example: 200 },
        content: {
          type: 'string',
          example: 'Container service UP!',
          description: 'Human-readable health message returned by the service.',
        },
      },
      required: ['code', 'status', 'content'],
      example: healthExample.response,
    },
    timestamp: {
      type: 'string',
      format: 'date-time',
      example: healthExample.timestamp,
    },
  },
  required: ['ok', 'response', 'timestamp'],
  example: healthExample,
};

docs(HealthcheckController, {
  classDecorators: [ApiTags('Healthcheck')],
  methods: {
    health: [
      ApiOperation({
        summary: 'Health check',
      }),
      ApiOkResponse({
        description: 'The service is healthy.',
        schema: healthResponseSchema,
      }),
    ],
  },
});
