name: portflow-nestJs

networks:
  portflow-net:
    driver: bridge

volumes:
  pg_data:
  mongo_data:
  redis_data:
  kafka_data:

services:
  # ---------------------------------------------------------------------------
  # PostgreSQL
  # ---------------------------------------------------------------------------
  postgresql:
    container_name: postgres
    image: postgres:18.3-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
      POSTGRES_EXTRA_DATABASES: >
        container_service_db
    ports:
      - "5432:5432"
    command: # Habilita replicação lógica necessária para CDC via Debezium
        - postgres
        - -c
        - wal_level=logical
        - -c
        - max_wal_senders=5
        - -c
        - max_replication_slots=5  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d admin"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    networks:
      - portflow-net

  # ---------------------------------------------------------------------------
  # MongoDB
  # ---------------------------------------------------------------------------
  mongodb:
    container_name: mongodb
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: terminal_service
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--username", "portflow", "--password", "portflow"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped  
    volumes:
      - ./mongo/init:/docker-entrypoint-initdb.d
      - mongo_data:/data/db
    networks:
      - portflow-net

  # ---------------------------------------------------------------------------
  # Redis
  # ---------------------------------------------------------------------------
  redis:
    container_name: redis
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    networks:
      - portflow-net

  # ---------------------------------------------------------------------------
  # Kafka (KRaft)
  # ---------------------------------------------------------------------------
  kafka:
    image: confluentinc/cp-kafka:7.8.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "29093:29093"
    environment:
      CLUSTER_ID: XVmXn3yFSg-B4UD_uAgnC2
      KAFKA_NODE_ID: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://kafka:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: kafka-broker-api-versions --bootstrap-server=localhost:9092 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped  
    networks:
      - portflow-net

  # ---------------------------------------------------------------------------
  # Kafka UI
  # ---------------------------------------------------------------------------
  kafka-ui:
    image: kafbat/kafka-ui:v1.5.0
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "kafka-ui"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: kafka-connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect:8083
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      kafka:
         condition: service_healthy
      kafka-connect:
         condition: service_healthy
    restart: unless-stopped  
    networks:
      - portflow-net

  # ---------------------------------------------------------------------------
  # Kafka Connect (Debezium)
  # ---------------------------------------------------------------------------
  kafka-connect:
    image: debezium/connect:2.7.3.Final
    container_name: kafka-connect
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: portflow-connect-cluster
      CONFIG_STORAGE_TOPIC: portflow_connect_configs
      OFFSET_STORAGE_TOPIC: portflow_connect_offsets
      STATUS_STORAGE_TOPIC: portflow_connect_statuses
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      REST_ADVERTISED_HOST_NAME: kafka-connect
      REST_PORT: 8083
      CONNECT_PLUGIN_PATH: /kafka/connect,/debezium-connector-postgres,/debezium-connector-mysql,/debezium-connector-mongodb,/debezium-connector-sqlserver,/debezium-connector-oracle
    depends_on:
      kafka:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8083/connectors || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20
    restart: unless-stopped  
    networks:
      - portflow-net

  # ---------------------------------------------------------------------------
  # Kong
  # ---------------------------------------------------------------------------   

  kong:
    image: kong:3.9.1
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_DECLARATIVE_CONFIG: /kong/kong.yaml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_TRACING_INSTRUMENTATIONS: all
      KONG_TRACING_SAMPLING_RATE: 1.0
    ports:
      - "8000:8000" # Proxy HTTP
      - "8001:8001" # Admin API HTTP
      - "8002:8002" #  UI
      - "8443:8443" #  Proxy HTTPS
      - "8444:8444" # Admin API HTTPS
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped  
    volumes:
      - ./kong:/kong:ro
    networks:
      - portflow-net

  # ---------------------------------------------------------------------------
  # Jaeger
  # ---------------------------------------------------------------------------
  jaeger:
    container_name: jaeger
    image: jaegertracing/jaeger:2.19.0
    ports:
      - '16686:16686'  # UI
      - '4317:4317'    # OTLP gRPC
      - '4318:4318'    # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: unless-stopped
    networks:
      - portflow-net
   
  # ---------------------------------------------------------------------------
  # Prometheus
  # ---------------------------------------------------------------------------
  prometheus:
      container_name: prometheus
      image: prom/prometheus:v3.11.3
      ports:
        - "9090:9090"
      volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      restart: unless-stopped
      networks:
        - portflow-net 


  # ---------------------------------------------------------------------------
  # Grafana
  # ---------------------------------------------------------------------------
  grafana:
      container_name: grafana
      image: grafana/grafana:11.5.10
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_SECURITY_ADMIN_USER=admin
      volumes:
        - ./grafana/provisioning:/etc/grafana/provisioning:ro
      depends_on:
        - prometheus
        - loki
        - jaeger
      networks:
        - portflow-net
  # ---------------------------------------------------------------------------
  # Loki
  # ---------------------------------------------------------------------------
  loki:
      container_name: loki
      image: grafana/loki:3.2.0
      ports:
        - "3100:3100"
      environment:
        - LOKI_CONFIG_FILENAME=/etc/loki/loki-local-config.yaml
      volumes:
        - ./loki/loki-config.yaml:/etc/loki/loki-local-config.yaml:ro
      networks:
        - portflow-net

  # ---------------------------------------------------------------------------
  # Promtail
  # ---------------------------------------------------------------------------
  promtail:
      container_name: promtail
      image: grafana/promtail:3.2.0
      command: -config.file=/etc/promtail/promtail.yaml
      volumes:
        - /var/lib/docker/containers:/var/lib/docker/containers:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./promtail/promtail.yaml:/etc/promtail/promtail.yaml:ro
      ports:
        - "9080:9080"
      depends_on:
        - loki
      networks:
        - portflow-net
