import { defineConfig } from 'jest';

export default defineConfig({
  rootDir: '.',
  testEnvironment: 'node',
  moduleFileExtensions: ['js', 'json', 'ts'],
  transform: {
    '^.+\\.ts$': ['ts-jest', { tsconfig: '<rootDir>/tsconfig.json' }],
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@Types/(.*)$': '<rootDir>/src/terminal/@types/$1',
    '^@Contracts/(.*)$': '<rootDir>/src/terminal/domain/contracts/$1',
    '^@Models/(.*)$': '<rootDir>/src/terminal/domain/models/$1',
    '^@Services/(.*)$': '<rootDir>/src/terminal/application/services/$1',
    '^@Infra/(.*)$': '<rootDir>/src/terminal/infrastructure/$1',
    '^@Shared/(.*)$': '<rootDir>/src/shared/$1',
  },
  projects: [
    {
      displayName: 'unit',
      testMatch: ['<rootDir>/**/*.{test,spec}.ts'],
      testPathIgnorePatterns: [
        '/node_modules/',
        '/dist/',
        '\\.integration\\.(test|spec)\\.ts$',
        '\\.e2e-(test|spec)\\.ts$',
      ],
      setupFiles: ['<rootDir>/test/unit/setup.unit.ts'],
      testTimeout: 5000,
    },
    {
      displayName: 'integration',
      testMatch: ['<rootDir>/**/*.integration.{test,spec}.ts'],
      testPathIgnorePatterns: [
        '/node_modules/',
        '/dist/',
        '(?<!\\.integration)\\.(test|spec)\\.ts$',
        '\\.e2e-(test|spec)\\.ts$',
      ],
      setupFiles: ['<rootDir>/test/integration/setup.integration.ts'],
      testTimeout: 30000,
    },
    {
      displayName: 'e2e',
      testMatch: ['<rootDir>/**/*.e2e-{test,spec}.ts'],
      testPathIgnorePatterns: [
        '/node_modules/',
        '/dist/',
        '\\.integration\\.(test|spec)\\.ts$',
      ],
      setupFiles: ['<rootDir>/test/e2e/setup.e2e.ts'],
      testTimeout: 30000,
    },
  ],
  coverageProvider: 'v8',
  coverageReporters: ['text', 'json', 'html', 'lcov'],
  collectCoverageFrom: [
    'src/**',
    '!node_modules/**',
    '!**/types/**',
    '!**/interfaces/**',
    '!**/contracts/**',
    '!**/constants/**',
    '!test/**',
    '!**.{test,spec}.ts',
    '!src/container/infrastructure/persistence/database/prisma/generated/**',
    '!**/*.d.ts',
    '!**/*.types.ts',
    '!**/*.type.ts',
    '!**/*.interface.ts',
    '!**/*.event.ts',
    '!**/*.events.ts',
    '!**/*.contract.ts',
    '!**/*.module.ts',
    '!main.ts',
    '!tracing.ts',
    '!**/*.dto.ts',
    '!**/*.docs.ts',
  ],
  verbose: true,
});
