@baseUrl= http://localhost:3333/api/v1
@kongUrl= http://localhost:8000/container-service



# ---------------------------------------------------------------------------
# Microservice isolado
# ---------------------------------------------------------------------------

# @name healthcheck_isolated
GET {{baseUrl}}/health

# ---------------------------------------------------------------------------
# Via Kong API Gateway
# ---------------------------------------------------------------------------

###

# @name healthcheck_gateway
GET {{kongUrl}}/health
