name: Container Service CI

on:
  workflow_dispatch:
  push:
    paths:
      - "microservices/container-service/**"
      - ".github/actions/setup-node/**"
      - ".github/workflows/container-service-ci.yaml"
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
    paths:
      - "microservices/container-service/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup NodeJs and PNPM
        uses: ./.github/actions/setup-node
        with:
          working-directory: ./microservices/container-service
      - name: Generate Prisma Client
        run: pnpm dlx prisma generate
        working-directory: ./microservices/container-service
        env:
          DATABASE_URL: "postgresql://admin:admin@localhost:5432/container_service_db_test"
      - name: Build Container Microservice
        run: pnpm build
        working-directory: ./microservices/container-service

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup NodeJs and PNPM
        uses: ./.github/actions/setup-node
        with:
          working-directory: ./microservices/container-service
      - name: Generate Prisma Client
        run: pnpm dlx prisma generate
        working-directory: ./microservices/container-service
        env:
          DATABASE_URL: "postgresql://admin:admin@localhost:5432/container_service_db_test"
      - name: Lint
        run: pnpm lint
        working-directory: ./microservices/container-service

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup NodeJs and PNPM
        uses: ./.github/actions/setup-node
        with:
          working-directory: ./microservices/container-service
      - name: Generate Prisma Client
        run: pnpm dlx prisma generate
        working-directory: ./microservices/container-service
        env:
          DATABASE_URL: "postgresql://admin:admin@localhost:5432/container_service_db_test"
      - name: Unit Tests
        run: pnpm test:unit:cov
        working-directory: ./microservices/container-service
        env:
          DATABASE_URL: postgresql://admin:admin@localhost:5432/container_service_db_test
          NODE_ENV: test

  integration-tests:
    runs-on: ubuntu-latest
    services:
      postgresql:
        image: postgres:18.3-alpine
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: container_service_db_test
        ports:
          - "5432:5432"
        options: >-
          --health-cmd "pg_isready -U admin -d container_service_db_test"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
      kafka:
        image: confluentinc/cp-kafka:7.8.0
        ports:
          - "29092:29092"
        env:
          CLUSTER_ID: XVmXn3yFSg-B4UD_uAgnC2
          KAFKA_NODE_ID: "1"
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup NodeJs and PNPM
        uses: ./.github/actions/setup-node
        with:
          working-directory: ./microservices/container-service
      - name: Generate Prisma Client
        run: pnpm dlx prisma generate
        working-directory: ./microservices/container-service
      - name: Integration Tests
        run: pnpm test:int
        working-directory: ./microservices/container-service
        env:
          DATABASE_URL: "postgresql://admin:admin@localhost:5432/container_service_db_test"
          NODE_ENV: test

  end-to-end-tests:
    runs-on: ubuntu-latest
    services:
      postgresql:
        image: postgres:18.3-alpine
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: container_service_db_test
        ports:
          - "5432:5432"
        options: >-
          --health-cmd "pg_isready -U admin -d container_service_db_test"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
      kafka:
        image: confluentinc/cp-kafka:7.8.0
        ports:
          - "29092:29092"
        env:
          CLUSTER_ID: XVmXn3yFSg-B4UD_uAgnC2
          KAFKA_NODE_ID: "1"
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup NodeJs and PNPM
        uses: ./.github/actions/setup-node
        with:
          working-directory: ./microservices/container-service
      - name: Generate Prisma Client
        run: pnpm dlx prisma generate
        working-directory: ./microservices/container-service
        env:
          DATABASE_URL: "postgresql://admin:admin@localhost:5432/container_service_db"
      - name: E2E Tests
        run: pnpm test:e2e
        working-directory: ./microservices/container-service
        env:
          DATABASE_URL: postgresql://admin:admin@localhost:5432/container_service_db_test
          NODE_ENV: test

  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup NodeJs and PNPM
        uses: ./.github/actions/setup-node
        with:
          working-directory: ./microservices/container-service
      - name: Generate Prisma Client
        run: pnpm dlx prisma generate
        working-directory: ./microservices/container-service
        env:
          DATABASE_URL: "postgresql://admin:admin@localhost:5432/container_service_db_test"
      - name: PNPM audit
        run: pnpm audit --audit-level=critical
        working-directory: ./microservices/container-service

  build-and-push:
    needs: [build, lint, unit-tests, integration-tests, end-to-end-tests, audit]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login on Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./microservices/container-service
          file: ./microservices/container-service/Dockerfile
          target: production
          push: true
          tags: |
            ghcr.io/nathanrodriguesvieira99/container-service:${{ github.sha }}
            ghcr.io/nathanrodriguesvieira99/container-service:latest
